[package]
name = "ouch"
version = "0.3.1"
authors = ["Vinícius Rodrigues Miguel <vrmiguel99@gmail.com>", "João M. Bezerra <marcospb19@hotmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/ouch-org/ouch"
license = "MIT"
keywords = ["decompression", "compression", "zip", "tar", "gzip"]
categories = ["command-line-utilities", "compression", "encoding"]
description = "A command-line utility for easily compressing and decompressing files and directories."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap        = "=3.0.0-beta.5" # Keep it pinned while in beta!
atty        = "0.2.14"
fs-err      = "2.6.0"
once_cell   = "1.8.0"
walkdir     = "2.3.2"
bzip2       = "0.4.3"
libc        = "0.2.103"
tar         = "0.4.37"
xz2         = "0.1.6"
zip         = { version =  "0.5.13", default-features = false, features = ["deflate-miniz"] }
flate2      = { version = "1.0.22", default-features = false, features = ["zlib"] }
zstd        = { version = "0.9.0", default-features = false, features = ["thin"] }

[build-dependencies]
clap = "=3.0.0-beta.5"
clap_generate = "=3.0.0-beta.5"

[dev-dependencies]
tempfile = "3.2.0"
infer = "0.5.0"
rand = { version = "0.8.3", default-features = false, features = ["small_rng", "std"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
